### ISSUE TITLE
Error in type annotations are ignored

### ISSUE THREAD

**Issue by Tobias-Buerger** [skogsbaer/write-your-python-program#2]
When you use invalid type annotations the extension doesn't warn you about it (Program does not run because of it -> it will cause a NameError).
Running it directly with python -i <file> shows the problem. This is a confusing behavior because students think everything is correct.

**Comment by skogsbaer** [comment]
This is on purpose. The extension runs the code with `from __future__ import annotations`
(see [PEP 563](https://www.python.org/dev/peps/pep-0563/)), which will be
the default from python 3.10 on anyway.

Currently, type annotations are not checked in any way, so it seems reasonable to also not check the types for existence. But the main reason why `from __future__ import annotations` is active is that otherwise methods of class cannot give a type to solve, without resorting to using strings as types.

Example:

```
class C:
    def foo(self: C):  # only works with `from __future__ import annotations`
        pass
```

I made this behavior clearer in the README.
